export const REPOS_REQUEST = "REPOS_REQUEST";
export const REPOS_SUCCESS = "REPOS_SUCCESS";
export const REPOS_FAILURE = "REPOS_FAILURE";

export const README_REQUEST = "README_REQUEST";
export const README_SUCCESS = "README_SUCCESS";
export const README_FAILURE = "README_FAILURE";

export const ISSUES_REQUEST =  "ISSUES_REQUEST";
export const ISSUES_SUCCESS =  "ISSUES_SUCCESS";
export const ISSUES_FAILURE =  "ISSUES_FAILURE";

export const PRS_REQUEST = "PRS_REQUEST";
export const PRS_SUCCESS = "PRS_SUCCESS";
export const PRS_FAILURE = "PRS_FAILURE";

export const SET_DETAIL_ITEM = "SET_DETAIL_ITEM"

export const RESET_POPUP = 'RESET_POPUP'
export const SET_POPUP = 'SET_POPUP'
export const SET_POPUP_OPEN = 'SET_POPUP_OPEN'